informer:
  command: java -version -Dtest.properties
  properties: 
    personSearch: person.csv
    vehicleSearch: vehicle.csv
    locationSearch: location.csv
relater:
  command: which java
  properties:
    objectSearch: object.csv
